nohup: bot.py: No such file or directory
nohup: bot.py: No such file or directory
nohup: bot.py: No such file or directory
nohup: bot.py: No such file or directory
nohup: bot.py: No such file or directory
nohup: bot.py: No such file or directory
./bot.py: line 1: import: command not found
from: can't read /var/mail/datetime
from: can't read /var/mail/threading
from: can't read /var/mail/scrape
from: can't read /var/mail/tabletext
./bot.py: line 7: API_KEY: command not found
./bot.py: line 8: chat_id: command not found
./bot.py: line 10: syntax error near unexpected token `('
./bot.py: line 10: `x = datetime.today()'
Traceback (most recent call last):
  File "/Users/vc/Documents/projects/telegram_crypto_bot/./bot.py", line 27, in <module>
    schedule.every().day.at("99:48").do(bot_message)
  File "/Users/vc/Documents/projects/telegram_crypto_bot/venv/lib/python3.9/site-packages/schedule/__init__.py", line 408, in at
    raise ScheduleValueError('Invalid time format')
schedule.ScheduleValueError: Invalid time format
